-- HDC Build 22.1
-- Provider-neutral authentication core required before migration 0001.
--
-- The original beta auth tables were created directly while the Neon backend
-- was being established. Keeping that prerequisite outside source control made
-- a clean rebuild impossible. This idempotent bootstrap records the exact
-- pre-0001 contract without changing an existing HDC database.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS public.hdc_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email citext NOT NULL UNIQUE,
  password_hash text NOT NULL,
  display_name text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  email_verified boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT hdc_users_status_check
    CHECK (status IN ('active', 'disabled', 'locked'))
);

CREATE TABLE IF NOT EXISTS public.hdc_user_roles (
  user_id uuid NOT NULL REFERENCES public.hdc_users(id) ON DELETE CASCADE,
  role text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role),
  CONSTRAINT hdc_user_roles_role_check CHECK (
    role IN (
      'customer', 'technician', 'seller', 'business',
      'admin', 'super_admin'
    )
  )
);

CREATE TABLE IF NOT EXISTS public.hdc_auth_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.hdc_users(id) ON DELETE CASCADE,
  token_jti uuid NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  last_seen_at timestamptz,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS hdc_auth_sessions_user_active_idx
  ON public.hdc_auth_sessions (user_id, expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS public.hdc_security_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.hdc_users(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  event_status text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT hdc_security_audit_metadata_object
    CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS hdc_security_audit_user_created_idx
  ON public.hdc_security_audit (user_id, created_at DESC);

-- These tables are server-owned. Flutter never receives a database role or a
-- connection string, and the restricted hdc_app workflow role receives no
-- direct grants to authentication or security-audit records.
REVOKE ALL ON public.hdc_users FROM PUBLIC;
REVOKE ALL ON public.hdc_user_roles FROM PUBLIC;
REVOKE ALL ON public.hdc_auth_sessions FROM PUBLIC;
REVOKE ALL ON public.hdc_security_audit FROM PUBLIC;

COMMIT;
